export const EMAIL_LIST_REQUEST = "EMAIL_LIST_REQUEST";
export const EMAIL_LIST_SUCCESS = "EMAIL_LIST_SUCCESS";
export const EMAIL_LIST_FAILURE = "EMAIL_LIST_FAILURE";

export const EMAIL_CONTENT_REQUEST = "EMAIL_CONTENT_REQUEST";
export const EMAIL_CONTENT_SUCCESS = "EMAIL_CONTENT_SUCCESS";
export const EMAIL_CONTENT_FAILURE = "EMAIL_CONTENT_FAILURE";
